FROM ubuntu:14.04

MAINTAINER berlius <berlius52@yahoo.com>

RUN apt-get update && apt-get install -y \
    libglib2.0-dev \
    libgl1-mesa-dev \
    libglu1-mesa-dev \
    libpng12-dev \
    git \
    wget \
    freeglut3-dev \
    libplib-dev \
    libopenal-dev \
    libpng12-dev \
    zlib1g-dev \
    libogg-dev \
    libvorbis-dev \
    g++ \
    libalut-dev \
    libxi-dev \
    libxmu-dev \
    libxrandr-dev \
    make \
    patch \
    xautomation  \
    python-numpy \
    python-scipy  \
    python-dev \
    python-nose \
    python-h5py  \
    python-pip \
    libopenblas-dev \
    cmake \
    zlib1g-dev \
    libjpeg-dev \
    xvfb \
    libav-tools \
    xorg-dev \
    python-opengl \
    libboost-all-dev \
    libsdl2-dev \
    swig \
    lxterminal
    
WORKDIR "/root"
   
ENV TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.11.0rc0-cp27-none-linux_x86_64.whl

RUN pip install --upgrade $TF_BINARY_URL 
RUN pip install Theano Keras 
 

RUN git clone https://github.com/openai/gym.git && \
    cd gym && \
    pip install -e . && \
    cd ..

RUN git clone https://github.com/ugo-nama-kun/gym_torcs && \
    cd gym_torcs/vtorcs-RL-color && \
    ./configure && \
    make && \
    make install && \
    make datainstall && \
    cd /root

COPY install.sh /root
RUN chmod +x /root/install.sh

WORKDIR "/root/sharedfolder"
CMD ["/bin/bash"]




